name: 'Maven publish'
on: [release]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
      - run: scp -r /maven/* root@51.158.65.226:/var/www/mavenrepos
